### ISSUE TITLE
Using render() twice in same process prints a warning

### ISSUE THREAD

**Issue by isaacs** [vadimdemedes/ink-testing-library#2]
> Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.

I've tried doing `unmount()` and `cleanup()` but I'm still getting this error.

When I use `rerender()`, it doesn't seem to be wiping away all of the state.  `render()` is giving me the correct output, but I get this warning.

Is there something I'm missing?  Some way to really truly tell it to start all the way over?

**Comment by mAAdhaTTah** [comment]
I'm getting the same issue. Since this lib is inspired by react-testing-library, something that allows us to [`require('ink-testing-library/cleanup-after-each')`](https://github.com/kentcdodds/react-testing-library/blob/master/cleanup-after-each.js) and wire up cleanup would be nice.

That said, I can also confirm that running `unmount` doesn't solve the problem.

**Comment by vadimdemedes** [comment]
Yep, that's a known problem - https://github.com/vadimdemedes/ink/issues/139. Unfortunately, I wasn't able to fix it yet. Unmounting, clearing up reconciler instances doesn't help indeed. I've tried implementing `act()` alternative for Ink, but couldn't get it to work. Any help is appreciated here!

**Comment by vadimdemedes** [comment]
Let's continue the convo at https://github.com/vadimdemedes/ink/issues/139.

**Comment by vadimdemedes** [comment]
Found the root cause of this issue, it's a React bug. See explanation at https://github.com/vadimdemedes/ink/issues/139#issuecomment-475116283.
